bcgov/nr-silva

.github/workflows/unit-tests.yml, frontend/package.json
---
[Frontend](https://nr-silva-68-frontend.apps.silver.devops.gov.bc.ca)
=> feat: generate coverage and pass to sonar cloud

.github/workflows/unit-tests.yml, docker-compose.yml, frontend/Dockerfile, frontend/package-lock.json, frontend/package.json
---
[Frontend](https://nr-silva-67-frontend.apps.silver.devops.gov.bc.ca)
=> Node 18 -> 20

docker-compose.yml
Run Caddy in Docker Compose.  The default behaviour is unchanged, bringing up the frontend is development mode.
To start Caddy instead: `docker compose up caddy`
---
[Frontend](https://nr-silva-74-frontend.apps.silver.devops.gov.bc.ca)
=> feat: optional Caddy in Docker Compose

frontend/src/components/AvatarImage/AvatarImage.scss, frontend/src/components/AvatarImage/index.tsx, frontend/src/components/BCHeaderwSide/index.tsx, frontend/src/components/MyProfile/MyProfile.scss, frontend/src/components/MyProfile/index.tsx, frontend/src/screens/Dashboard/index.tsx
Added the User Profile sidebar with test data and cleaned up the Dashboard
Fixes # [SILVA-170](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-170)
---
[Frontend](https://nr-silva-78-frontend.apps.silver.devops.gov.bc.ca)
=> Added the User Profile sidebar with test data and cleaned up the Dashboard

frontend/src/index.tsx
Fix broken Carbon Design style.
This was tested locally.
---
[Frontend](https://nr-silva-87-frontend.apps.silver.devops.gov.bc.ca)
=> fix: update carbon design class prefix changed

.github/workflows/analysis.yml
Add maven command for testing.
Fixes #111 
Tested locally.
---
[Backend](https://nr-silva-113-backend.apps.silver.devops.gov.bc.ca)
[Frontend](https://nr-silva-113-frontend.apps.silver.devops.gov.bc.ca)
=> ci: add maven command test for back end

.github/workflows/pentests.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
New workflow for penetration tests using ZAProxy.  Runs by cronjob or manual dispatch.  Attaches ZAP reports to runs and creates issues as necessary.
---
[Backend](https://nr-silva-117-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-117-frontend.apps.silver.devops.gov.bc.ca)
=> feat: penetration tests and reporting

.github/workflows/analysis.yml
* bump bcgov-nr/action-test-and-analyse-java to v1.0.0
* add triggers for running or not
* use temurin for java 21
---
[Backend](https://nr-silva-121-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-121-frontend.apps.silver.devops.gov.bc.ca)
=> deps: update Java test action, triggers, temurin w/ java 21

.github/workflows/merge.yml, .github/workflows/pr-open.yml, backend/openshift.deploy.yml, frontend/openshift.deploy.yml
Fix prod parameters and remove promote variable.
This should be tested with this PR.
---
[Backend](https://nr-silva-133-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-133-frontend.apps.silver.devops.gov.bc.ca)
=> Fix: prod parameters deployment and promote

frontend/openshift.deploy.yml
Mysterious errors were causing PROD images to keep being reused for the Frontend, even when there should have been changes.  Looks like there were some template breaks, which this fixes.
---
[Backend](https://nr-silva-209-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-9-frontend.apps.silver.devops.gov.bc.ca)
=> fix: frontend template corrections

backend/openshift.deploy.yml, frontend/openshift.deploy.yml
Horizontal pod autoscalers are not being cleaned up, because of missing labels.
---
[Backend](https://nr-silva-210-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-10-frontend.apps.silver.devops.gov.bc.ca)
=> fix: add labels to autoscalers for cleanup

.github/workflows/pr-close.yml
Add missing config maps.
Will be tested with this PR.
---
[Backend](https://nr-silva-218-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-18-frontend.apps.silver.devops.gov.bc.ca)
=> fix: add config maps in the delete oc command

.github/workflows/pr-close.yml
Fixes `PR close` workflow with FAM PR number.
This will be tested once we merge this in.
---
Deployment number, if any: 25
[Backend](https://nr-silva-25-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-25-frontend.apps.silver.devops.gov.bc.ca)
=> fix: pr close workflow

.github/workflows/analysis.yml
The file below is provided by Oracle, so we're not responsible for CodeQL's inability to scan it.  There's no real exclude so the file is deleted in our CodeQL job.
`backend/InstallCert.java`
---
Backend: https://nr-silva-239-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-39-frontend.apps.silver.devops.gov.bc.ca
=> fix(ci): exclude Oracle-provided file from CodeQL

.github/workflows/merge.yml, .github/workflows/pr-open.yml, backend/openshift.deploy.yml, backend/pom.xml, backend/src/main/java/ca/bc/gov/restapi/results/config/SecurityConfig.java, backend/src/main/java/ca/bc/gov/restapi/results/config/SwaggerConfig.java, backend/src/main/java/ca/bc/gov/restapi/results/exception/UserNotFoundException.java, backend/src/main/java/ca/bc/gov/restapi/results/security/IdentityProvider.java, backend/src/main/java/ca/bc/gov/restapi/results/security/LoggedUserService.java, backend/src/main/java/ca/bc/gov/restapi/results/security/UserAuthenticationHelper.java, backend/src/main/java/ca/bc/gov/restapi/results/security/UserInfo.java, backend/src/main/java/ca/bc/gov/restapi/results/service/OpeningService.java, backend/src/main/resources/application.properties, backend/src/test/java/ca/bc/gov/restapi/results/endpoint/OpeningEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/security/UserAuthenticationHelperTest.java, backend/src/test/java/ca/bc/gov/restapi/results/security/UserInfoTest.java, backend/src/test/java/ca/bc/gov/restapi/results/security/UserServiceTest.java, backend/src/test/java/ca/bc/gov/restapi/results/service/OpeningServiceTest.java, backend/src/test/resources/application.properties, docker-compose.yml
Add FAM authentication in the backend.
⚠️ Note that from now on, everytime you go to Swagger UI you'll have to input a JWT token.
Fixes [Jira ticket SILVA-313](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-313)
Tested running locally and with unit tests.
---
Backend: https://nr-silva-243-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-43-frontend.apps.silver.devops.gov.bc.ca
=> feat: add backend FAM authentication

.github/workflows/pr-open.yml, backend/openshift.deploy.yml, backend/src/main/resources/application.properties
We've been running out of connections.  This puts connection pool settings into envars, making a cap=1 easier for PRs.
---
Backend: https://nr-silva-257-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-7-frontend.apps.silver.devops.gov.bc.ca
=> chore(ci): set min and max db (oracle) connections

backend/src/main/java/ca/bc/gov/restapi/results/postgres/dto/OpeningsPerYearDto.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/dto/OpeningsPerYearFiltersDto.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/endpoint/DashboardMetricsEndpoint.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/entity/OpeningsLastYearEntity.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/repository/OpeningsLastYearRepository.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/service/DashboardMetricsService.java, backend/src/main/resources/db/migration/V4__update_metrics_charts_tables.sql, backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/DashboardMetricsEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/service/DashboardMetricsServiceTest.java, backend/src/test/resources/application.properties
jira issue silva-331
Create resource to fetch Openings Per Year.
Fixes [Jira Task SILVA-331](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-331)
Tested locally;
---
Backend: https://nr-silva-263-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-13-frontend.apps.silver.devops.gov.bc.ca
=> feat: openings per year api

frontend/package.json, frontend/vite.config.ts
Handle: `The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.`
Fixes #216 
---
Backend: https://nr-silva-295-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-45-frontend.apps.silver.devops.gov.bc.ca
=> fix: CJS build of Vide's Node API is deprecated

backend/openshift.deploy.yml, backend/src/main/java/ca/bc/gov/restapi/results/common/config/CorsConfig.java, backend/src/main/resources/application.properties, backend/src/test/resources/application.properties
Simply add CORS configuration policy and allowed origins.
Fixes no issue.
Eyeball.
---
Backend: https://nr-silva-305-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-5-frontend.apps.silver.devops.gov.bc.ca
=> feat: enable cors config

backend/src/main/java/ca/bc/gov/restapi/results/postgres/repository/OpeningsLastYearRepository.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/service/DashboardMetricsService.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/service/DashboardMetricsServiceTest.java
- Fixes a bug when searching for the freegrowing milestones using the client number filter;
- Fixes a bug of showing data from the wrong starting month on the opening trends chart;
Fixes [Jira issue SILVA-392](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-392)
Testes locally.
---
Backend: https://nr-silva-310-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-10-frontend.apps.silver.devops.gov.bc.ca
=> fix: opening metrics bugs

frontend/src/components/BCHeaderwSide/index.tsx, frontend/src/components/BarChartGrouped/index.jsx, frontend/src/components/DonutChartView/index.jsx, frontend/src/components/FavouriteCard/index.tsx, frontend/src/components/OpeningScreenDataTable/index.jsx, frontend/src/screens/Landing/index.tsx, frontend/src/screens/Opening/index.tsx, frontend/src/services/AuthService.ts
- Fixed login issue (when the user is already logged in and tried to click the login button);
- Fixed warnings related to react components and props;
- Removed the address when clicked on the favourite cards;
Fixes [Jira issue SILVA-389](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-389)
Tested locally.
---
Backend: https://nr-silva-307-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-7-frontend.apps.silver.devops.gov.bc.ca
=> chore: react warnings and login issues

.github/workflows/merge.yml, .github/workflows/pr-open.yml, backend/openshift.deploy.yml, common/openshift.fluentbit.yml, database/openshift.deploy.yml, frontend/openshift.deploy.yml
Devops updates:
- OpenShift deploymentConfigs have been deprecated, so move to deployments instead
- Drop imageStreams (simpler!)
=> chore(ci): deploymentConfig deprecation, drop imageStreams

frontend/src/components/BarChartGrouped/index.tsx, frontend/src/components/OpeningMetricsTab/index.tsx, frontend/src/components/OpeningScreenDataTable/index.tsx, frontend/src/components/OpeningsTab/index.tsx, frontend/src/services/OpeningService.ts
- Fixes warnings when running locally.
Stopped to look at the charts, understanding why they don't have data locally. Here's why:
- When we started using the real backend locally, instead of test, no data was fetched from Oracle. In simple words, there's no data locally to be displayed.
- But when looking into that, some warnings could be noticed. **This PR aims on fixing them** 
Tested locally,
---
Backend: https://nr-silva-323-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-23-frontend.apps.silver.devops.gov.bc.ca
[Main Merge Workflow](https://github.com/bcgov/nr-silva/actions/workflows/me …
=> chore: React warning fixes

backend/src/main/java/ca/bc/gov/restapi/results/common/dto/OracleExtractionDto.java, backend/src/main/java/ca/bc/gov/restapi/results/common/dto/OracleLogDto.java, backend/src/main/java/ca/bc/gov/restapi/results/common/security/UserAuthenticationHelper.java, backend/src/main/java/ca/bc/gov/restapi/results/common/service/DashboardExtractionService.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/OpeningService.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/dto/DashboardFiltersDto.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/endpoint/DashboardExtractionEndpoint.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/endpoint/DashboardMetricsEndpoint.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/service/DashboardInsertionService.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/service/DashboardMetricsService.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/DashboardExtractionEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/DashboardMetricsEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/UserOpeningEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/service/DashboardMetricsServiceTest.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/service/UserOpeningServiceTest.java
Just fixing typos. (I've found a new VSCode extension, my new friend).
No tests required.
- VSCode extension: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
- Canadian Dictionary: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-canadian-english
---
Backend: https://nr-silva-326-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-26-frontend.apps.silver.devops.gov.bc.ca
=> chore: fix typos

frontend/package-lock.json, frontend/package.json, frontend/src/__test__/components/BCHeader.test.tsx, frontend/src/__test__/components/MyRecentActions.test.tsx, frontend/src/__test__/components/OpeningScreenDataTable.test.tsx, frontend/src/__test__/components/StatusTag.test.tsx, frontend/src/components/BCHeader/index.tsx, frontend/src/components/MyRecentActions/index.tsx, frontend/src/components/StatusTag/index.tsx, frontend/src/services/OpeningService.ts, frontend/src/types/RecentOpening.ts
- Just adding unit tests to React components with [Vitest](https://vitest.dev/api/).
Fixes [SILVA-447](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-447)
- Unit tests added.
---
Backend: https://nr-silva-329-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-29-frontend.apps.silver.devops.gov.bc.ca
=> test: silva 447 add unit tests

.github/workflows/pr-open.yml
For backend in particular:
``` pr-open.yml
verification_retry_attempts: 5
verification_retry_seconds: 15
```
=> chore(ci): extend backend verification time and attempts

.github/workflows/merge.yml, backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchResponseDto.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepository.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepositoryTest.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/service/OpeningServiceTest.java
- Add Regen Delay dates Filter;
- Add Free Growing Early and Late dates Filter;
Fixes [SILVA-467](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-467) and [SILVA-468](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-468)
Tested locally and added unit and integration tests
---
Backend: https://nr-silva-361-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-11-frontend.apps.silver.devops.gov.bc.ca
=> feat: add free growing and regen delay filters

backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchResponseDto.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpoint.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepository.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepositoryTest.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/service/OpeningServiceTest.java
Fixes [SILVA-490](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-490)
- Tested locally
- Tested with unit tests;
---
Backend: https://nr-silva-368-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-18-frontend.apps.silver.devops.gov.bc.ca
=> fix: forest file id, duplication results and pagination

backend/openshift.deploy.yml, database/openshift.deploy.yml, frontend/openshift.deploy.yml
Fix for stale image bug.  Seems to be a kubernetes issue that images are updated, but not correctly rolled out.
=> fix(ci): stale images

frontend/package-lock.json, frontend/package.json
`npm warn deprecated @types/react-leaflet@3.0.0: This is a stub types definition. react-leaflet provides its own type definitions, so you do not need this installed.`
---
Backend: https://nr-silva-380-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-30-frontend.apps.silver.devops.gov.bc.ca
=> chore(ci): types/react-leaflet deprecated

.github/workflows/merge.yml, .github/workflows/pr-open.yml
---
Backend: https://nr-silva-406-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-6-frontend.apps.silver.devops.gov.bc.ca
=> chore: overwriting deployments

backend/src/main/resources/application.yml
This change should fix the migration issue
---
Backend: https://nr-silva-408-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-8-frontend.apps.silver.devops.gov.bc.ca
=> fix: fixing deploy config

frontend/openshift.deploy.yml, frontend/src/screens/Landing/index.tsx
The login page notification is a good way to communicate with users about the current status of the application, but as it is not yet completed, it is better to be removed until the implementation is complete.
---
Backend: https://nr-silva-433-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-33-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-554): removing notification from landing page

.github/CODEOWNERS, frontend/src/screens/DashboardRedirect/index.tsx
After discussion, it was decided to remove the Org Unit Selection from the screen that appears right after login. For the soft launch, there's no need to select an org unit at that point as there's no create opening functionality in place.
---
Backend: https://nr-silva-435-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-35-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-557): removing org unit selection after login

.github/workflows/analysis.yml
---
Backend: https://nr-silva-438-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-38-frontend.apps.silver.devops.gov.bc.ca
=> chore(ci): switch to GH CodeQL, allow Trivy to fail (temp)

backend/src/main/java/ca/bc/gov/restapi/results/oracle/SilvaOracleConstants.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchFiltersDto.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchResponseDto.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepository.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/dto/UserRecentOpeningDto.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/endpoint/UserRecentOpeningEndpoint.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/entity/UserRecentOpeningEntity.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/repository/UserRecentOpeningRepository.java, backend/src/main/java/ca/bc/gov/restapi/results/postgres/service/UserRecentOpeningService.java, backend/src/test/java/ca/bc/gov/restapi/results/postgres/service/UserRecentOpeningServiceTest.java
Feature: Recent Openings History for the nr-silva Application
This pull request implements the backend logic to track and retrieve recently viewed openings by users in the nr-silva application.
Changes Made:
User Interaction Tracking:
Whenever a user views an opening, the interaction is logged in the user_recent_openings table within the PostgreSQL database.
This table stores data such as the opening ID and the lastViewTime to track the user's recent activities.
Recent Openings Retrieval:
A backend service has been added to retrieve the list of recently viewed openings for a specific user, sorted by lastViewTime.
This functionality is intended to be used by the frontend to display a "Recent Openings" table, though it is not part of this PR.
Fixes # 
SILVA-524: …
=> feat: user recent openings backend

frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/index.tsx
Changed icon and text when no results found during search
---
Backend: https://nr-silva-458-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-8-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-565): fixed empty results screen for silviculture search

frontend/src/components/SilvicultureSearch/Openings/OpeningsSearchBar/index.tsx
Closed the advanced search dropdown when user clicks on search button
---
Backend: https://nr-silva-459-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-9-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-566): close advanced search when user click on search

frontend/package-lock.json, frontend/package.json, frontend/src/__test__/components/FriendlyDate.test.tsx, frontend/src/components/FriendlyDate/index.tsx, frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/index.tsx, frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/testData.ts, frontend/src/contexts/PaginationProvider.tsx
- Make the disturbance date column visible by default
- Use the date format provided by Atlassian for dates
- Fix the items per page of the opening search to be 20 items per page. 
---
Backend: https://nr-silva-460-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-10-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-562): fixing search result size and  value

backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/CodeDescriptionDto.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpoint.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/OpenCategoryCodeService.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpointTest.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/service/OpenCategoryCodeServiceTest.java, frontend/src/__test__/components/FriendlyDate.test.tsx, frontend/src/__test__/components/SilvicultureSearch/Openings/OpeningSearchBar.test.tsx, frontend/src/__test__/components/SilvicultureSearch/Openings/SearchScreenDataTable.test.tsx, frontend/src/__test__/components/TruncatedText.test.tsx, frontend/src/components/FriendlyDate/index.tsx, frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/index.tsx, frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/testData.ts, frontend/src/components/TruncatedText/index.tsx, frontend/src/types/TableHeader.ts
Added the ability to truncate text
---
Backend: https://nr-silva-456-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-6-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-449): truncating text based on parent

frontend/src/__test__/components/SilvicultureSearch/Openings/OpeningSearchBar.test.tsx, frontend/src/__test__/components/SilvicultureSearch/Openings/OpeningSearchTab.test.tsx, frontend/src/components/SilvicultureSearch/Openings/OpeningsSearchBar/OpeningsSearchBar.scss, frontend/src/components/SilvicultureSearch/Openings/OpeningsSearchBar/index.tsx, frontend/src/components/SilvicultureSearch/Openings/OpeningsSearchTab/index.tsx, frontend/src/components/TruncatedText/index.tsx
Added a message to notify the user in case no parameter was provided and prevented the search from happening if no parameter was provided.
---
Backend: https://nr-silva-461-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-11-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-536): fixing missing notification when no param provided

frontend/src/__test__/components/SilvicultureSearch/Openings/AdvancedSearchDropdown.test.tsx, frontend/src/components/SilvicultureSearch/Openings/AdvancedSearchDropdown/index.tsx
Fixing a misleading label in the advanced search on silviculture
---
Backend: https://nr-silva-465-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-15-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-567): fixing label

frontend/src/__test__/components/PageTitle.test.tsx, frontend/src/components/BCHeaderwSide/constants.ts, frontend/src/components/BCHeaderwSide/index.tsx, frontend/src/components/PageTitle/index.tsx
Fixed an issue with the side nav bar that was always closed. Also added breadcrumbs to the top of the pages
---
Backend: https://nr-silva-467-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-17-frontend.apps.silver.devops.gov.bc.ca
=> fix(SILVA-564): added breadcrumb and updated menu

.github/workflows/pr-open.yml, .github/workflows/pr-validate.yml
Move pr description add and conditional commit check into pr-validate.yml, which relies on a shared job in bcgov/quickstart-openshift-helpers.
---
- [Backend](https://nr-silva-487-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-37-frontend.apps.silver.devops.gov.bc.ca)
=> ci: pr-validate job

.github/workflows/.deploy.yml, .github/workflows/merge.yml, .github/workflows/pr-close.yml
Make sure deployments happen for main merge.  Only trigger conditionally for PRs.  Also remove database from image promotions, since we're not buildint that anymore.
---
- [Backend](https://nr-silva-493-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-43-frontend.apps.silver.devops.gov.bc.ca)
=> fix(ci): merge triggers, promotions

.github/workflows/.deploy.yml, .github/workflows/merge.yml
---
- [Backend](https://nr-silva-494-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-44-frontend.apps.silver.devops.gov.bc.ca)
=> fix(ci): allowed_origins different for TEST and PROD

frontend/src/__test__/components/TableRowComponent.test.tsx, frontend/src/components/ActionButtons/index.tsx, frontend/src/components/Dashboard/Opening/RecentOpeningsDataTable/index.tsx, frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/index.tsx, frontend/src/components/TableRowComponent/index.tsx
Fixing modal on recent openings
---
- [Backend](https://nr-silva-515-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-15-frontend.apps.silver.devops.gov.bc.ca)
=> fix(SILVA-575): fixing modal on recent openings

.github/workflows/analysis.yml, .github/workflows/merge.yml, .github/workflows/pr-open.yml, .github/workflows/pr-validate.yml
---
- [Backend](https://nr-silva-521-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-21-frontend.apps.silver.devops.gov.bc.ca)
=> ci: stop allowing merge workflow interrupts

frontend/src/__test__/components/Dashboard/Opening/RecentOpeningsDataTable.test.tsx, frontend/src/components/Dashboard/Opening/RecentOpeningsDataTable/index.tsx, frontend/src/components/OpeningsMap/index.tsx, frontend/src/components/OpeningsTab/index.tsx
Enabling the use of maps on recent openings
---
- [Backend](https://nr-silva-524-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-24-frontend.apps.silver.devops.gov.bc.ca)
=> fix(SILVA-582): enabling map on recent openings

frontend/src/__test__/services/AuthService.test.ts, frontend/src/contexts/AuthProvider.tsx, frontend/src/services/AuthService.ts
---
- [Backend](https://nr-silva-529-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-29-frontend.apps.silver.devops.gov.bc.ca)
=> fix: fixing auth context refresh

backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningRepository.java, frontend/src/__test__/components/SilvicultureSearch/Openings/OpeningSearchBar.test.tsx, frontend/src/__test__/components/SilvicultureSearch/Openings/OpeningSearchTab.test.tsx, frontend/src/components/SilvicultureSearch/Openings/OpeningsSearchBar/index.tsx
Removing timber mark from the quick search bar. From now on, it can only be searched through the advanced search
---
- [Backend](https://nr-silva-538-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-38-frontend.apps.silver.devops.gov.bc.ca)
- [Merge …
=> fix(SILVA-591): removing timber mark from quick search

frontend/src/__test__/components/SilvicultureSearch/Openings/OpeningSearchBar.test.tsx, frontend/src/components/SilvicultureSearch/Openings/AdvancedSearchDropdown/index.tsx
Fixing datepicker on advanced search behavior
---
- [Backend](https://nr-silva-539-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-39-frontend.apps.silver.devops.gov.bc.ca)
=> fix(SILVA-549): fixing date picker on advanced search

frontend/src/components/RecentOpenings/OpeningRow.tsx, frontend/src/utils/DateUtils.ts
for consistency, if the "disturbance start date" is null then the table should show a place holder text `—` instead of empty cell
Current:
---
- [Backend](https://nr-silva-628-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-28-frontend.apps.silver.devops.gov.bc.ca)
=> fix: empty disturbance date on recent openings table

frontend/src/components/SilvicultureSearch/OpeningSearch/index.tsx
Redirect from bar chart was broken with the empty search block, clicking on a bar would lead to the search screen with error message saying at least one filter is required, this PR addresses that problem.
---
- [Backend](https://nr-silva-665-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-15-frontend.apps.silver.devops.gov.bc.ca)
=> fix: redirect from bar chart

frontend/src/__test__/components/SilvicultureSearch/OpeningSearch.test.tsx, frontend/src/components/PageTitle/styles.scss, frontend/src/components/SilvicultureSearch/OpeningSearch/index.tsx, frontend/src/components/SilvicultureSearch/OpeningSearch/styles.scss
Closes #694 
Address the following issues:
- Ensure that clicking "Clear Filters" resets the search and returns the page to an empty state.
- CP and Timber Mark are disappearing at different breakpoints or zoom - increase padding to 48px (use rem) to remain visible
Issues below are determined to be no fix:
- The org unit (or any multiselect/combobox) focus remains pressed after using it 
- this is an issue with carbon itself
- Make the modal dropdowns overlap the content when opened - this way the user doesn't need to scroll through the modal and the dropdown. 
- Again an issue with Carbon's composed modal itself. It wasn't possible for me to find a way to make this work for all screen sizes within reasonable time. so we have to compromise by letting user scroll further down to select a …
=> fix: #694 dev task fix search issues

frontend/src/components/ActionButtons/index.tsx, frontend/src/components/Card/CardItem/index.tsx, frontend/src/components/Card/CardTitle/styles.scss, frontend/src/components/FavoriteButton/ActionableFavouriteButton/index.tsx, frontend/src/components/OpeningTableRow/index.tsx, frontend/src/components/SilvicultureSearch/OpeningSearch/OpeningSearchBar.tsx, frontend/src/components/SilvicultureSearch/OpeningSearch/index.tsx, frontend/src/constants/tableConstants.ts, frontend/src/contexts/NotificationProvider.tsx
Completes: #724
Address the following problems:
Pagination on the Opening Search page does not work as expected. Clicking the next page shows no results.
Search results are being cached and should not be.
Favorite and unfavorite actions should always trigger a toast notification.
Unfavouriting an opening from the detail title results in an error.
---
- [Backend](https://nr-silva-725-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-25-frontend.apps.silver.devops.gov.bc.ca)
- [Merge …
=> fix: #724 bugfix opening search and favourite actions

backend/src/main/java/ca/bc/gov/restapi/results/oracle/SilvaOracleQueryConstants.java
Fixing a query issue that returned multiple results when an opening has multiple cut blocks
---
- [Backend](https://nr-silva-728-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-28-frontend.apps.silver.devops.gov.bc.ca)
=> fix: fixed details query

frontend/src/__test__/components/OpeningDetails/OpeningOverview.test.tsx, frontend/src/components/OpeningDetails/OpeningOverview/index.tsx, frontend/src/components/OpeningDetails/OpeningOverview/styles.scss, frontend/src/constants/index.ts
Completes #731 
- Updated the overview tab with the updated design in Figma
- Changed place holder text from em dash to 2 dashes
---
- [Backend](https://nr-silva-732-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-32-frontend.apps.silver.devops.gov.bc.ca)
=> fix: #731 dev task adjust opening overview layout

frontend/src/components/Card/CardItem/index.tsx
use definition tooltip to let users know they can hover a text and see the definition, as requested by @mariafernanda31 
---
- [Backend](https://nr-silva-734-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-34-frontend.apps.silver.devops.gov.bc.ca)
=> fix: use definition tooltip for card item

backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/opening/OpeningDetailsTenuresDto.java, backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/opening/details/OpeningDetailsTenureService.java, backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningEndpointIntegrationTest.java
Completes: #777 
Added the totalUnfiltered value to the tenure endpoint
---
- [Backend](https://nr-silva-778-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-28-frontend.apps.silver.devops.gov.bc.ca)
=> fix: #777 dev task include total of all tenures in the tenure endpoint

frontend/src/components/OpeningDetails/OpeningStandardUnits/SpeciesTooltipList.tsx
Forgot to add `m` after min height 
---
- [Backend](https://nr-silva-796-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-46-frontend.apps.silver.devops.gov.bc.ca)
=> fix: add unit meter to ssu species def-tooltip

frontend/src/components/BarChartTooltip/index.scss, frontend/src/components/BarChartTooltip/index.tsx, frontend/src/components/OpeningSubmissionTrend/constants.tsx, frontend/src/components/OpeningSubmissionTrend/styles.scss
Completes: #631 
Updated the barchart popup with the design on figma, this update also corrects the dark mode setting for the popup (use colour tokens instead of hardcoded colour code). 
Note: there are some slight differences still:
- the code style display is a mismatch from the design, either BC Sans does not provide its own code-style or it's due to our css setup
- the colour of bars in the chart are not exactly from the specification on figma, Figma uses a static colour code instead of a colour token.
---
- [Backend](https://nr-silva-837-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-37-frontend.apps.silver.devops.gov.bc.ca)
Please create PRs in draft mode.  Mark as ready to …
=> fix: #631 dev task bar chart popover style update

frontend/src/components/OpeningsMapEntryPopup/index.tsx, frontend/src/components/OpeningsMapEntryPopup/styles.scss
This change fixes the spacing between lines in the map popup of the openings. Currently, we do not have a Figma design for this popup.
The proposed change is as follows:
Fixes #802 
---
- [Backend](https://nr-silva-832-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-32-frontend.apps.silver.devops.gov.bc.ca)
=> fix(#802): fix content spacing on openings map entry popup

.github/workflows/.deploy.yml, .github/workflows/pr-open.yml
In PRs e2e should only run if there was a deployment.
---
- [Backend](https://nr-silva-907-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-7-frontend.apps.silver.devops.gov.bc.ca)
=> chore(ci): deploy trigger for e2e

frontend/src/components/OpeningDetails/OpeningForestCover/index.tsx, frontend/src/components/OpeningDetails/OpeningForestCover/styles.scss, frontend/src/components/OpeningDetails/OpeningSummary/index.tsx, frontend/src/components/OpeningsMap/index.tsx, frontend/src/components/OpeningsMap/styles.scss, frontend/src/components/OpeningsMapEntryPopup/index.tsx, frontend/src/screens/Openings/OpeningDetails/index.tsx, frontend/src/types/MapLayer.ts
This change implements the map improvements for the forest cover tab on the opening details page. 
Fixes #979 
---
- [Backend](https://nr-silva-996-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-46-frontend.apps.silver.devops.gov.bc.ca)
=> feat(#979): add forest cover map improvements
