bcgov/nr-silva

.github/workflows/merge-main.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/unit-tests.yml
frontend/openshift.deploy.yml

---
[Frontend](https://nr-silva-9-frontend.apps.silver.devops.gov.bc.ca/) available

ci: simplify, remove matrices from workflows

---

frontend/.gitignore
frontend/src/components/ThemeToggle/ThemeToggle.scss
frontend/src/components/ThemeToggle/index.tsx
frontend/src/screens/Landing/index.tsx

Added the toggle theme button with the new custom appearance as request by the team. Added the toggleButton to the home page for now, just for demonstration purposes.
Fixes # SILVA-137 (https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-137)

Added the toggle button on the home page for demostration

---

.github/workflows/unit-tests.yml

Comment out failing tests.
Please undo these changes once tests have been fixed! @RMCampos @jazzgrewal

ci: comment out failing tests (make sure to fix!)

---

.github/workflows/unit-tests.yml

Set up frontend and backend code for SonarCloud.  Backend code is commented out, since the backend isn't written yet.  SonarCloud is preconfigured, since the required projects aren't ready yet.
See issue https://github.com/bcgov/nr-silva/issues/16 for more info.
---
[Frontend](https://nr-silva-20-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Frontend](https://nr-silva-20-frontend.apps.silver.devops.gov.bc.ca/) available
Once merged, …

feat: frontend sonar cloud

---

docker-compose.yml

Run with `docker-compose up`.
---
[Frontend](https://nr-silva-18-frontend.apps.silver.devops.gov.bc.ca/) available

feat: Docker Compose live reload

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
.github/workflows/unit-tests.yml

Polish up TEST and PROD deployments.  First pass.
---
[Frontend](https://nr-silva-28-frontend.apps.silver.devops.gov.bc.ca/) available

feat: test and prod

---

frontend/Caddyfile

https://github.com/bcgov/nr-silva/issues/32
---
[Frontend](https://nr-silva-33-frontend.apps.silver.devops.gov.bc.ca/) available

bug: caddy connect-src

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
frontend/Caddyfile
frontend/openshift.deploy.yml

---
[Frontend](https://nr-silva-34-frontend.apps.silver.devops.gov.bc.ca/) available

feat: pass github secrets to caddy envars

---

frontend/src/components/BCHeaderwSide/index.tsx
frontend/src/components/ThemeToggle/ThemeToggle.scss
frontend/src/screens/Landing/index.tsx

Changed the icon sizes and padding of the toggle theme switch and deleted it from the Landing page, added to the navbar, which is the BCHeaderwSide component.
Fixes # SILVA-137(https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-137)
---
[Frontend](https://nr-silva-38-frontend.apps.silver.devops.gov.bc.ca/) available

Changed the toggle size, and addded it to the navbar

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
frontend/Caddyfile
frontend/openshift.deploy.yml

Causing a problem.  Reverting.
---
[Frontend](https://nr-silva-40-frontend.apps.silver.devops.gov.bc.ca/) available

Revert "feat: pass github secrets to caddy envars (#34)"

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
frontend/openshift.deploy.yml
frontend/src/aws-exports.js

This fixes the bug where users are redirected to localhost after a successful login on OpenShift.
---
[Frontend](https://nr-silva-39-frontend.apps.silver.devops.gov.bc.ca)

bug: REACT_APP_URL for redirect

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
frontend/Caddyfile
frontend/openshift.deploy.yml

---
[Frontend](https://nr-silva-41-frontend.apps.silver.devops.gov.bc.ca)

feat: pass github secrets to caddy envars (try 2)

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
frontend/Caddyfile
frontend/openshift.deploy.yml

Fix AWS Cognito URL address to be grabbed from Github Variables.
This will be tested once this PR is open and get merged!
---
[Frontend](https://nr-silva-43-frontend.apps.silver.devops.gov.bc.ca)

fix: aws cognito url

---

frontend/src/aws-exports.js

Fix redirect URL according to current location.
Tested locally!
---
[Frontend](https://nr-silva-48-frontend.apps.silver.devops.gov.bc.ca)

fix: redirect login url

---

frontend/.github/CODEOWNERS

---
[Frontend](https://nr-silva-50-frontend.apps.silver.devops.gov.bc.ca)

Codeowners

---

.github/workflows/unit-tests.yml
frontend/Dockerfile

Node versions inconsistent.  See issue.
UPDATE: Bonus!  v18 in our test action solved a failing test.  :D
---
[Frontend](https://nr-silva-52-frontend.apps.silver.devops.gov.bc.ca)
---
[Frontend](https://nr-silva-52-frontend.apps.silver.devops.gov.bc.ca)

feat: line up node versions

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-silva/pull/62
https://github.com/bcgov/nr-silva/pull/63
https://github.com/bcgov/nr-silva/pull/64
---
[Frontend](https://nr-silva-65-frontend.apps.silver.devops.gov.bc.ca)

fix(security) Dependabot security patches

---

docker-compose.yml
frontend/src/services/AuthService.ts

Fix FAM for DEV (locally) and TEST (Test openshift namespace).
⚠️ AWS doesn't allow wildcards, so we can't have settings for DEV, since every address will depends on the PR number. So the best option is to run locally with Docker Compose, then later reach the deployed TEST version.
This was tested locally.
---
[Frontend](https://nr-silva-66-frontend.apps.silver.devops.gov.bc.ca)

feat: get fam working on dev and test

---

.github/workflows/unit-tests.yml

---
[Frontend](https://nr-silva-70-frontend.apps.silver.devops.gov.bc.ca)

ci: bump bcgov-nr/action-test-and-analyse

---

frontend/package-lock.json

Reverts bcgov/nr-silva#69
---
[Frontend](https://nr-silva-71-frontend.apps.silver.devops.gov.bc.ca)

Revert "chore(deps): lock file maintenance"

---

docker-compose.yml
frontend/src/aws-exports.js

fixed the redirectSignOut using the env vars to dynamically create logout url, so the logout functionality is working no matter which environment it is being run on
Fixes # [SILVA-171](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-171)
---
[Frontend](https://nr-silva-75-frontend.apps.silver.devops.gov.bc.ca)

fixed the redirectSignOut using the env vars to dynamically create logout url

---

frontend/src/components/BCHeaderwSide/index.tsx
frontend/src/components/ThemeToggle/ThemeToggle.scss

Fixed the sizing issues with the themeToggle button
Fixes # [SILVA-137](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-137)
---
[Frontend](https://nr-silva-89-frontend.apps.silver.devops.gov.bc.ca)

fixed the sizing issue for the themeToglle button to align with the Figma design

---

.github/dependabot.yml

---
[Frontend](https://nr-silva-95-frontend.apps.silver.devops.gov.bc.ca)

ci: disable Dependabot in favour of Renovate

---

.github/workflows/merge-main.yml

---
[Frontend](https://nr-silva-97-frontend.apps.silver.devops.gov.bc.ca)

feat: auto-create issues for penetration tests

---

.github/workflows/merge-main.yml

Revising.  Errors in first attempt.

ci: pen test reporting

---

.github/workflows/merge-main.yml

---
[Frontend](https://nr-silva-101-frontend.apps.silver.devops.gov.bc.ca)

bug: set specific token permissions for ZAP, duplicate issues

---

frontend/package-lock.json
frontend/package.json

Addresses Dependabot [alert](https://github.com/bcgov/nr-silva/security/dependabot/11).
---
[Backend](https://nr-silva-114-backend.apps.silver.devops.gov.bc.ca)
[Frontend](https://nr-silva-114-frontend.apps.silver.devops.gov.bc.ca)

deps: bump vitest for vulnerable get-func-name

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

Add CodeQL analysis.
---
[Backend](https://nr-silva-116-backend.apps.silver.devops.gov.bc.ca)
[Frontend](https://nr-silva-116-frontend.apps.silver.devops.gov.bc.ca)

feat: CodeQL

---

.github/workflows/merge.yml

Fix Main merge workflow.
Will be tested once it get merged.
---
[Backend](https://nr-silva-128-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-128-frontend.apps.silver.devops.gov.bc.ca)

fix: merge main workflow name

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
backend/openshift.deploy.yml
backend/pom.xml
backend/src/main/resources/application.properties
backend/src/main/resources/data.sql
backend/src/test/resources/application.properties
common/openshift.init.yml
database/Dockerfile
database/openshift.deploy.yml
docker-compose.yml

Add empty Postgres database in the backend.
Fixes [Jira Task 221](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-221)
Tested locally with Docker Compose.
---
[Backend](https://nr-silva-129-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-129-frontend.apps.silver.devops.gov.bc.ca)

Feat: add database

---

.github/workflows/pr-close.yml

Add missing image promotion to TEST;
This will be tested once merged.
---
[Backend](https://nr-silva-130-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-130-frontend.apps.silver.devops.gov.bc.ca)

ci: add missing image promotions to TEST

---

.github/workflows/merge.yml

Fix `prod` deployment workflow.
This will get tested once merged.
---
[Backend](https://nr-silva-132-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-132-frontend.apps.silver.devops.gov.bc.ca)

fix: prod deployment

---

.github/workflows/merge.yml

---
[Backend](https://nr-silva-135-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-135-frontend.apps.silver.devops.gov.bc.ca)

Fix: verification paths in main merge

---

.gitignore
backend/pom.xml
frontend/openshift.deploy.yml

---
[Backend](https://nr-silva-171-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-171-frontend.apps.silver.devops.gov.bc.ca)

fix(ci): wrong repo name

---

backend/Dockerfile
frontend/Dockerfile

Issues in main merge.  Starting by replacing a few images.
---
[Backend](https://nr-silva-172-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-172-frontend.apps.silver.devops.gov.bc.ca)

ci: trigger frontend and backend builds

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-silva/security/code-scanning/43
https://github.com/bcgov/nr-silva/security/dependabot/16

deps: bump axios for follow-redirects

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-silva/security/code-scanning/41
https://github.com/bcgov/nr-silva/security/dependabot/14
---
[Backend](https://nr-silva-179-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-179-frontend.apps.silver.devops.gov.bc.ca)

deps: bump @testing-library/jest-dom for @adobe/css-tools

---

.github/workflows/pr-open.yml
common/openshift.init.yml

---
[Backend](https://nr-silva-31-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-31-frontend.apps.silver.devops.gov.bc.ca)

ci: rotate through 50 PR numbers for FAM

---

.github/workflows/merge.yml
common/openshift.init.yml

Fix TEST and PROD deployments failing.
Fixes #183 
This change will be tested as soon as this PR gets merged.
---
[Backend](https://nr-silva-34-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-34-frontend.apps.silver.devops.gov.bc.ca)

bug: investigate test workflow

---

.github/workflows/pr-close.yml
README.md

PR number mod 50 hadn't been set up in PR close!
---
[Backend](https://nr-silva-35-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-35-frontend.apps.silver.devops.gov.bc.ca)

fix: PR/ZONE numbers inconsistent

---

backend/pom.xml

https://github.com/bcgov/nr-silva/security/code-scanning/39
---
[Backend](https://nr-silva-41-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-41-frontend.apps.silver.devops.gov.bc.ca)

chore(deps): vulnerabilities

---

frontend/Caddyfile

---
[Backend](https://nr-silva-42-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-42-frontend.apps.silver.devops.gov.bc.ca)

fix: Caddyfile wildcard

---

frontend/Caddyfile

Still at it.
---
[Backend](https://nr-silva-43-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-43-frontend.apps.silver.devops.gov.bc.ca)

bug: Caddy CSPs

---

.github/workflows/pr-close.yml

Adjust rotating PR numbers (mod 50) for oc cleanup.  Related to FAM.

fix: rotating PR numbers for oc cleanup

---

.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
frontend/openshift.deploy.yml

Rotating PR numbers has been causing stale images to deploy.  This PR dials that down to only changing routes.
---
[Backend](https://nr-silva-208-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-8-frontend.apps.silver.devops.gov.bc.ca)

bug: revisit routes

---

backend/pom.xml
backend/src/main/java/ca/bc/gov/restapi/results/Controller.java
common/openshift.fluentbit.yml
common/openshift.init.yml

Task related to jira ticket 270 at https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-270
Enable existing backend REST API to send logs to OpenSearch observability tool.
⚠️ note that was created a simple controller with a `/test` api for testing purposes.
Fixes [Jira Ticket 270](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-270)
This was tested locally.
Screenshot running locally:
---
[Backend](https://nr-silva-217-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Frontend](https://nr-silva-17-frontend.apps.silver.devops.gov.bc.ca)
[Main Merge Workflow](https://github.com/bcgov/nr-silva/actions/workflows/merge-main.y …

feat: enable backend logs to be sent to opensearch

---

.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

Stop overriding ZONE values for FOM PR number recycling.  Instead change only the route.
---
Backend: https://nr-silva-27-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-27-frontend.apps.silver.devops.gov.bc.ca

fix(ci): stale images

---

.github/workflows/analysis.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

Fix duplicate runs of CodeQL and make some config updates.
---
Backend: https://nr-silva-238-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-38-frontend.apps.silver.devops.gov.bc.ca

chore(ci): codeQL updates

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

---
Backend: https://nr-silva-240-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-40-frontend.apps.silver.devops.gov.bc.ca

chore(ci): combine CodeQL jobs and work on unsuccessful exclusion

---

backend/src/main/java/ca/bc/gov/restapi/results/endpoint/OpeningEndpoint.java
backend/src/main/java/ca/bc/gov/restapi/results/entity/OpeningEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/service/OpeningService.java
backend/src/test/java/ca/bc/gov/restapi/results/endpoint/OpeningEndpointTest.java
backend/src/test/java/ca/bc/gov/restapi/results/service/OpeningServiceTest.java

If there are no Openings for the current user (authenticated), the API will return a list from the latest openings sorted by the creation date (descendant).
Fixes [Jira Issue SILVA-326](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-326)
Tested locally and added Unit and Integration test cases.
---
Backend: https://nr-silva-247-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-47-frontend.apps.silver.devops.gov.bc.ca

feat: include latest openings if no openings for the user

---

frontend/Caddyfile
frontend/openshift.deploy.yml

Stale var.  Closes https://github.com/bcgov/nr-silva/issues/253.
---
Backend: https://nr-silva-254-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-4-frontend.apps.silver.devops.gov.bc.ca

chore(ci): drop VITE_QUESTIONS_API_KEY var

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningEndpoint.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningEndpointTest.java

jira issue silva-373
Add header `x-opening-source` providing information either where the opening did came from the logged user or not. Possible values are:
- `user-based` when openings in the response **DID** get created by the logged user;
- `not-user-based` when openings in the response **DID NOT** get created by the logged user. In this case, the response body will container no filter by user, but respond with latest ones instead.
Fixes [Jira task SILVA-373](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-373)
This was tested locally and with unit tests.
---
Backend: https://nr-silva-262-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: …

feat: add x-opening-source header

---

.github/workflows/pr-open.yml

Builds were accidentally commented out.
---
Backend: https://nr-silva-275-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-25-frontend.apps.silver.devops.gov.bc.ca

fix(ci): uncomment builds

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

---
Backend: https://nr-silva-276-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-26-frontend.apps.silver.devops.gov.bc.ca

chore(ci): update deployer action

---

.github/workflows/merge.yml

---
Backend: https://nr-silva-277-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-27-frontend.apps.silver.devops.gov.bc.ca

chore(ci): merge timeout deployment faile

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-silva/security/code-scanning/48
https://github.com/bcgov/nr-silva/security/dependabot/21
---
Backend: https://nr-silva-283-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-33-frontend.apps.silver.devops.gov.bc.ca

chore(deps): bump axios for follow-redirects

---

backend/pom.xml

---
Backend: https://nr-silva-282-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-32-frontend.apps.silver.devops.gov.bc.ca

chore(deps): misc

---

backend/Dockerfile

---
Backend: https://nr-silva-302-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-2-frontend.apps.silver.devops.gov.bc.ca

chore(deps): bump backend base

---

backend/src/main/java/ca/bc/gov/restapi/results/common/config/SwaggerConfig.java

Add link on Swagger with steps to get a bearer token.
No tests required;
---
Backend: https://nr-silva-312-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-12-frontend.apps.silver.devops.gov.bc.ca

chore: add steps to get bearer token for swagger

---

frontend/package-lock.json
frontend/package.json

---
Backend: https://nr-silva-347-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-47-frontend.apps.silver.devops.gov.bc.ca

chore(deps): bump deps for security alerts

---

.github/workflows/merge.yml

Add missing parameter.
No need.
---
Backend: https://nr-silva-358-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-8-frontend.apps.silver.devops.gov.bc.ca

ci: add missing parameter value

---

.github/workflows/pr-close.yml

---
Backend: https://nr-silva-384-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-34-frontend.apps.silver.devops.gov.bc.ca

chore(ci): handle gh runner oc removal

---

README.md
frontend/package-lock.json
frontend/package.json
frontend/src/__test__/components/BCHeader.test.tsx
frontend/src/__test__/components/BCHeaderwSide.test.tsx
frontend/src/__test__/components/BarChartGrouped.test.tsx
frontend/src/__test__/components/MyRecentActions.test.tsx
frontend/src/__test__/components/OpeningScreenDataTable.test.tsx
frontend/src/__test__/screens/Opening.test.tsx
frontend/src/__test__/views/LoginOrgSelection.test.tsx
frontend/src/amplifyconfiguration.ts
frontend/src/components/BCHeader/index.tsx
frontend/src/components/BCHeaderwSide/constants.ts
frontend/src/components/MyRecentActions/index.tsx
frontend/src/components/OpeningScreenDataTable/index.tsx
frontend/src/components/OpeningsTab/index.tsx
frontend/src/components/OrganizationSelection/index.tsx
frontend/src/services/AuthService.ts
frontend/src/services/SecretsService.ts
frontend/src/types/RecentOpening.ts
frontend/vitest.config.ts

- Add code coverage report to SonarCloud (Already existing, I'd say)
- Add badges in the readme file.
Fixes [SILVA-510](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-510)
- No needed
---
Backend: https://nr-silva-390-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-40-frontend.apps.silver.devops.gov.bc.ca

docs: add badges in the readme

---

backend/src/main/java/ca/bc/gov/restapi/results/common/config/ConstantsConfig.java
backend/src/main/java/ca/bc/gov/restapi/results/common/exception/MaxPageSizeException.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchFiltersDto.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchResponseDto.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpoint.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/enums/OpeningStatusEnum.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepository.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/OpeningService.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/repository/OpeningSearchRepositoryTest.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/service/OpeningServiceTest.java

- Handle missing Opening Search filters:
- **Cutting permit id** filter
- **Cut block id** filter
- **Up to 2000** page size
- Removed **EntryUserId** and added **MyOpenings** so when asked, the backend get the current user from the token.
- **Status** can be one or more
- **Acronym** - Still in progress, but will be finished soon!
Fixes [SILVA-507](https://apps.nrs.gov.bc.ca/int/jira/browse/SILVA-507)
- Tested locally
- Added unit testing
---
Backend: https://nr-silva-387-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-37-frontend.apps.silver.devops.gov.bc.ca
[Main Merge …

fix: opening filters

---

backend/Dockerfile
backend/dockerfile-entrypoint.sh
backend/openshift.deploy.yml
common/openshift.init.yml

Changed the certificate extraction for Oracle. Moved from the internal Java file to the init container service instead.
---
Backend: https://nr-silva-398-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-48-frontend.apps.silver.devops.gov.bc.ca
---
Backend: https://nr-silva-398-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: …

fix(certextract): changing certificate extraction to use init container

---

backend/src/main/resources/application.yml
docker-compose.yml

…e for the application.yml file of springboot
---
Backend: https://nr-silva-402-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-2-frontend.apps.silver.devops.gov.bc.ca
[Main Merge Workflow](https://github.com/bcgov/nr-silva/actions/workflows/merge- …

changed the postgres variables to align local with the test environment, and same for the application.yml for the spring boot

---

backend/openshift.deploy.yml

Added the rate limiter configuration to the backend
---
Backend: https://nr-silva-404-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-4-frontend.apps.silver.devops.gov.bc.ca

feat(SILVA-530): added rate limiter to the backend

---

.github/CODEOWNERS

---
Backend: https://nr-silva-405-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-5-frontend.apps.silver.devops.gov.bc.ca

chore: removing @RMCampos from the codeowners

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
common/openshift.init.yml

Cleaned up db password variable database naming conventions and resolved password update bug.
- [ x] Bug fix (non-breaking change which fixes an issue)
Tested by the pipeline.
- [ x] Test A
---
Backend: https://nr-silva-414-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-14-frontend.apps.silver.devops.gov.bc.ca

fix: password update error

---

.github/CODEOWNERS

added Greg Pascucci as codeowner
---
Backend: https://nr-silva-415-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-15-frontend.apps.silver.devops.gov.bc.ca

chore: added new developer to codeowners

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/ClientAcronymEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/CutBlockOpenAdminEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/OpenCategoryCodeEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/OpeningAttachmentEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/OpeningEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/OrgUnitEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/ResultsElectronicSubmissionEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/postgres/entity/OpeningsActivityEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/postgres/entity/OpeningsLastYearEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/postgres/entity/OracleExtractionLogsEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/postgres/entity/UserOpeningEntity.java

---
Backend: https://nr-silva-430-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-30-frontend.apps.silver.devops.gov.bc.ca

chore: fixing entity by adding the schemas

---

frontend/src/components/BCHeaderwSide/constants.ts
frontend/src/screens/DashboardRedirect/index.tsx
frontend/src/screens/Opening/index.tsx

Removing the code just to keep the code cleaner and safer with only the content required for soft launch.
---
Backend: https://nr-silva-429-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-29-frontend.apps.silver.devops.gov.bc.ca

fix: removing code not required for the soft launch

---

frontend/src/components/FavouriteCard/index.tsx
frontend/src/components/FavouriteCard/styles.scss
frontend/src/screens/Opening/index.tsx

disabled some of the home buttons as they're not required right now
---
Backend: https://nr-silva-434-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-34-frontend.apps.silver.devops.gov.bc.ca

fix(SILVA-494): disabling home buttons

---

.github/workflows/merge.yml

---
Backend: https://nr-silva-436-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-36-frontend.apps.silver.devops.gov.bc.ca

chore: forcing overwrite for most entries

---

.github/workflows/.deploy.yml
.github/workflows/analysis.yml
.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

Use runs-on: ubuntu-latest for all GitHub runners.  This was previously inconsistent.

ci: use runs-on: ubuntu-latest

---

frontend/src/__test__/components/SilvicultureSearch/Openings/AdvancedSearchDropdown.test.tsx
frontend/src/__test__/utils/multiSelectSortUtils.test.ts
frontend/src/components/SilvicultureSearch/Openings/AdvancedSearchDropdown/index.tsx
frontend/src/utils/multiSelectSortUtils.ts

Added description to the dropdown info for org unit and category
---
Backend: https://nr-silva-457-backend.apps.silver.devops.gov.bc.ca/actuator/health
Frontend: https://nr-silva-7-frontend.apps.silver.devops.gov.bc.ca

fix(SILVA-550): added description to orgunit and category

---

.github/workflows/merge.yml

Error setting up package promotion.  My bad!  Thankfully it was non-breaking.
---
- [Backend](https://nr-silva-492-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-42-frontend.apps.silver.devops.gov.bc.ca)

fix(ci): promotion package error

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/SilvaOracleConstants.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/OpeningSearchFiltersDto.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpoint.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/OpenCategoryCodeEntity.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningRepository.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/OpenCategoryCodeService.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningSearchEndpointTest.java
frontend/src/components/SilvicultureSearch/Openings/AdvancedSearchDropdown/index.tsx
frontend/src/components/SilvicultureSearch/Openings/SearchScreenDataTable/index.tsx
frontend/src/services/search/openings.ts

Fixed the search query when searching for multiple values. Also, added the missing parameters for the status and the list of status that are excluded.
This PR includes:
- SILVA-528
- SILVA-583
- SILVA-584
- SILVA-585
---
- [Backend](https://nr-silva-517-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-17-frontend.apps.silver.devops.gov.bc.ca)
---
- …

fix(SILVA-528): fixing query and status params

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningRepository.java

Fixing queries
---
- [Backend](https://nr-silva-526-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-26-frontend.apps.silver.devops.gov.bc.ca)

fix(SILVA-584): fixing queries

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningRepository.java

---
- [Backend](https://nr-silva-527-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-27-frontend.apps.silver.devops.gov.bc.ca)

fix(SILVA-584): fixing query count

---

frontend/src/constants/tableConstants.ts

Fixed the column  client number to show just the client name
---
- [Backend](https://nr-silva-530-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-30-frontend.apps.silver.devops.gov.bc.ca)

chore: changing column to client name

---

frontend/src/components/AutocompleteClientLocation/index.tsx

---
- [Backend](https://nr-silva-516-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-16-frontend.apps.silver.devops.gov.bc.ca)
- [Merge …

chore: testing autocomplete

---

.github/workflows/.deploy.yml
.github/workflows/analysis.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

---
- [Backend](https://nr-silva-550-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-0-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): actions moved to bcgov org

---

.github/workflows/.deploy.yml
.github/workflows/analysis.yml
.github/workflows/merge.yml
.github/workflows/pentests.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

---
- [Backend](https://nr-silva-552-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-2-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): use GH runner ubuntu-24.04

---

.github/ISSUE_TEMPLATE/bugfix.yml
.github/ISSUE_TEMPLATE/decision.yml
.github/ISSUE_TEMPLATE/dev.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/epic.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/question.yml
.github/ISSUE_TEMPLATE/ux.yml

---
- [Backend](https://nr-silva-557-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-7-frontend.apps.silver.devops.gov.bc.ca)

chore: fixing templates

---

.github/CODEOWNERS

---
- [Backend](https://nr-silva-587-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-37-frontend.apps.silver.devops.gov.bc.ca)
- [Merge …

chore(ci): update codeowners

---

backend/pom.xml
backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/UserActionsEndpoint.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/OpeningTrendsService.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/UserActionsEndpointIntegrationTest.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/service/OpeningTrendsServiceTest.java

Updating dependencies to fix some security issues
---
- [Backend](https://nr-silva-586-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-36-frontend.apps.silver.devops.gov.bc.ca)

chore(deps): updating dependencies

---

backend/pom.xml

Fix and closes #585 #584 and #583
Security Vulnerabilities Fix
This pull request addresses and fixes several security vulnerabilities identified in the repository. The following CVEs have been resolved:
(CVE-2024-50379)[https://avd.aquasec.com/nvd/cve-2024-50379]
(CVE-2024-56337)[https://avd.aquasec.com/nvd/cve-2024-56337]
Description: Remote Code Execution (RCE) vulnerability due to a Time-of-Check Time-of-Use (TOCTOU) flaw in JSP compilation.
Severity: High
(CVE-2024-12798)[https://avd.aquasec.com/nvd/cve-2024-12798]
Description: Authorization Bypass vulnerability due to case-sensitive comparisons.
Severity: Medium
(CVE-2024-38827)[https://avd.aquasec.com/nvd/cve-2024-38827]
Description: Arbitrary Code Execution via JaninoEventEvaluator in logback-core.
Severity: Medium …

chore(deps:sec): updating dependencies due to security

---

frontend/package-lock.json
frontend/package.json

---
- [Backend](https://nr-silva-598-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-48-frontend.apps.silver.devops.gov.bc.ca)

chore(deps:sec): updating security dependency issue

---

.github/pull_request_template.md
backend/src/main/java/ca/bc/gov/restapi/results/common/endpoint/GlobalErrorResponseEndpoint.java
backend/src/main/java/ca/bc/gov/restapi/results/common/exception/InvalidOpeningIdException.java
backend/src/main/java/ca/bc/gov/restapi/results/postgres/service/UserRecentOpeningService.java
backend/src/main/resources/application.yml
backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/OpeningFavoriteEndpointIntegrationTest.java
backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/UserRecentOpeningEndpointIntegrationTest.java
backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/UserRecentOpeningEndpointTest.java
backend/src/test/java/ca/bc/gov/restapi/results/postgres/service/UserRecentOpeningServiceTest.java

This pull request introduces a robust error-handling mechanism for our backend by implementing the Problem Details response format (RFC 7807). With this change, error responses will now include the proper MIME type (`application/problem+json`) and a consistent format, making it easier for client applications to parse and handle errors automatically. This streamlines debugging and logging and enhances overall API interoperability by adhering to a widely accepted standard.
The benefits of this approach are clear: standardized error responses lead to improved error diagnosis, more maintainable code, and better alignment with industry practices. For more details on the standard, check out the official [RFC 7807](https://tools.ietf.org/html/rfc7807) and additional guidelines in the [Problem …

fix(600): bugfix all errors are reported as 401 on the backend

---

.github/workflows/.deploy.yml
backend/openshift.deploy.yml
common/openshift.database.yml
frontend/openshift.deploy.yml

---
- [Backend](https://nr-silva-618-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-18-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): update openshift resources by environment and deprecate cpu/memory limits

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml

---
- [Backend](https://nr-silva-621-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-21-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): simplify use of .deploy.yml

---

.github/workflows/pr-open.yml
backend/openshift.deploy.yml
frontend/openshift.deploy.yml

---
- [Backend](https://nr-silva-622-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-22-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): fix autoscaler

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
frontend/openshift.deploy.yml

---
- [Backend](https://nr-silva-623-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-23-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): dial down backend cpu requests

---

frontend/src/components/OpeningSubmissionTrend/index.tsx
frontend/src/types/OpeningTypes.ts
frontend/src/utils/DateUtils.ts

Added a date util function to get the month abbreviation given a month number
---
- [Backend](https://nr-silva-626-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-26-frontend.apps.silver.devops.gov.bc.ca)

fix: month abbv name in trend graph

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningRepository.java
frontend/src/components/RecentOpenings/OpeningRow.tsx
frontend/src/types/OpeningTypes.ts

Fixed an issue with the count query for the search by opening ids used by the recent openints
Fixes #632 632
---
- [Backend](https://nr-silva-633-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-33-frontend.apps.silver.devops.gov.bc.ca)

fix(632): fixed count query for search by opening ids

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/OpeningRepository.java

Closes #632
---
- [Backend](https://nr-silva-634-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-34-frontend.apps.silver.devops.gov.bc.ca)

chore(632): fixing merge conflicted query

---

frontend/src/__test__/components/SilvicultureSearch/OpeningSearch.test.tsx
frontend/src/components/SilvicultureSearch/OpeningSearch/OpeningSearchBar.tsx
frontend/src/components/SilvicultureSearch/OpeningSearch/index.tsx
frontend/src/components/SilvicultureSearch/OpeningSearch/styles.scss
frontend/src/styles/default-components.scss

Fixes #661
Hover
Expanded
Disabled date pickers
Map icon
Empty search feedback
---
- [Backend](https://nr-silva-662-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-12-frontend.apps.silver.devops.gov.bc.ca)

fix: #661 bugfix opening search visual fix

---

backend/src/test/java/ca/bc/gov/restapi/results/postgres/endpoint/UserRecentOpeningEndpointIntegrationTest.java
frontend/src/App.tsx
frontend/src/components/ActionButtons/index.tsx
frontend/src/components/BCHeaderwSide/index.tsx
frontend/src/components/ChartContainer/index.tsx
frontend/src/components/CustomMultiSelect/index.tsx
frontend/src/components/FavoriteButton/ActionableFavouriteButton/index.tsx
frontend/src/components/FavoriteButton/index.tsx
frontend/src/components/FavouriteOpenings/index.tsx
frontend/src/components/PageTitle/index.tsx
frontend/src/components/SilvicultureSearch/OpeningSearch/OpeningFilterBar.tsx
frontend/src/components/SilvicultureSearch/OpeningSearch/OpeningSearchBar.tsx
frontend/src/components/SilvicultureSearch/OpeningSearch/index.tsx
frontend/src/components/SilvicultureSearch/hooks.ts
frontend/src/components/StatusTag/index.tsx
frontend/src/contexts/AuthProvider.tsx
frontend/src/screens/Dashboard/index.tsx
frontend/src/screens/Openings/OpeningDetails/index.tsx
frontend/src/services/OpeningSearchService.ts
frontend/src/services/OpeningService.ts

Fixing the issues raised by SonarCloud on the backend and the frontend.
Fixes #375 
---
- [Backend](https://nr-silva-706-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-6-frontend.apps.silver.devops.gov.bc.ca)

fix: #375 fix SonarCloud issues

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/OpeningSearchService.java

Fixing search total value. It was a small issue when recreating the page after processing it
Fixes #713
---
- [Backend](https://nr-silva-717-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-17-frontend.apps.silver.devops.gov.bc.ca)

fix(713): fixing search total value

---

frontend/src/components/OpeningDetails/OpeningStandardUnits/AccordionTitle.tsx
frontend/src/components/OpeningDetails/OpeningStandardUnits/index.tsx
frontend/src/components/OpeningDetails/OpeningStandardUnits/styles.scss
frontend/src/screens/Openings/OpeningDetails/index.tsx
frontend/src/services/OpeningDetailsService.ts
frontend/src/services/apiConfig.ts
frontend/src/types/OpeningTypes.ts

This change implements the frontend integration for opening standard units.
Fixes #699 
---
- [Backend](https://nr-silva-735-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-35-frontend.apps.silver.devops.gov.bc.ca)
---
- [Backend](https://nr-silva-735-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- …

feat(699): dev task integrate standard unit endpoint

---

.github/workflows/.deploy.yml
.github/workflows/analysis.yml
.github/workflows/merge.yml
.github/workflows/pentests.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

Intended to address several security alerts.
---
- [Backend](https://nr-silva-741-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-41-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): workflow permissions

---

backend/src/main/java/ca/bc/gov/restapi/results/oracle/SilvaOracleQueryConstants.java
frontend/src/components/OpeningTableRow/index.tsx

---
- [Backend](https://nr-silva-743-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-43-frontend.apps.silver.devops.gov.bc.ca)

chore: fixing graph search discrepancy and new tab opening

---

.github/CODEOWNERS
.github/workflows/pr-validate.yml
frontend/package-lock.json
frontend/package.json

---
- [Backend](https://nr-silva-752-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-2-frontend.apps.silver.devops.gov.bc.ca)

chore: fixing sec issues

---

backend/src/main/java/ca/bc/gov/restapi/results/ResultsApplication.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/SilvaOracleQueryConstants.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/SimplePageDto.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/opening/OpeningDetailsTenureDto.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/dto/opening/OpeningDetailsTenuresDto.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningEndpoint.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/entity/opening/OpeningTenureProjection.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/repository/CutBlockOpenAdminRepository.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/opening/details/OpeningDetailsService.java
backend/src/main/java/ca/bc/gov/restapi/results/oracle/service/opening/details/OpeningDetailsTenureService.java
backend/src/test/java/ca/bc/gov/restapi/results/oracle/endpoint/OpeningEndpointIntegrationTest.java
docs/Silva.postman_collection.json
frontend/src/types/OpeningTypes.ts

This PR introduces a new tenure endpoint for retrieving detailed tenure information related to openings. Key changes include:
- Adding new frontend DTO types to represent tenure data.
- Implementing backend service and repository queries to support tenure details.
- Adding integration tests covering the new tenure endpoints.
- Fixes #758 
---
- [Backend](https://nr-silva-770-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-20-frontend.apps.silver.devops.gov.bc.ca)
- [Merge …

feat(#758): adding tenure endpoint for details

---

frontend/src/components/OpeningDetails/TenureIdentification/index.tsx
frontend/src/screens/Openings/OpeningDetails/index.tsx

Forgot to display the `--` instead of null
---
- [Backend](https://nr-silva-779-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-29-frontend.apps.silver.devops.gov.bc.ca)

fix: use place holder for null and undefined in tenure tab

---

frontend/src/components/Comments/index.tsx
frontend/src/components/OpeningDetails/OpeningActivities/ActivityDetail/index.tsx
frontend/src/components/OpeningDetails/OpeningActivities/DisturbanceDetail.tsx
frontend/src/components/OpeningDetails/OpeningOverview/index.tsx

This change replaces manual comment entries with the new `Comments` component for readability and reusability. 
Fixes #795 
---
- [Backend](https://nr-silva-801-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-1-frontend.apps.silver.devops.gov.bc.ca)

feat(#795): replace comment entries with comments component

---

backend/pom.xml

This change enables hot reload for the Spring Boot backend application. The backend would restart automatically when a change is made and saved (Command + S on Mac).
I read the followings should be enabled on Intellij for hot reload to work. But mine worked without enabling the options.
- Enable the flag: File > Settings > Build, Execution, Deployment > Compiler > Build project automatically
- Turn on the flag: File > Settings > Advanced Settings > Allow auto-make to start even if developed application is currently running
Fixes #800 
---
- [Backend](https://nr-silva-810-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-10-frontend.apps.silver.devops.gov.bc.ca)
Please create PRs in …

feat(#800): enable hot reload for backend application

---

backend/Dockerfile
docker-compose.yml
frontend/Dockerfile

---
- [Backend](https://nr-silva-826-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-26-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): drop docker pins

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

---
- [Backend](https://nr-silva-843-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-43-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): drop allowlisted actions pins

---

.github/workflows/e2e.yml
.github/workflows/pr-open.yml

---
- [Backend](https://nr-silva-876-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Frontend](https://nr-silva-26-frontend.apps.silver.devops.gov.bc.ca)

chore(ci): fix e2e workflow permissions
